version: '3.1'

services:
  postgres:
    image: postgres:13.10
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: polinom
      POSTGRES_PASSWORD: sweetpok1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network

  user-service:
    build:
      context: ./lms-2
      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: polinom
      SPRING_DATASOURCE_PASSWORD: sweetpok1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - my-network

  nextjs:
    build:
      context: ./nextjs-front
      dockerfile: Dockerfile
    container_name: nextjs-front
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network: